spring:
    profiles: development
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/spring_boot_db
        username: postgres
        password: password
    jpa:
        show-sql: true
        test-on-borrow: true
        properties:
          hibernate:
            cache.use_second_level_cache: false
            cache.use_query_cache: false
            generate_statistics: true
            hbm2ddl.auto: create
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
            show_sql: true

